### ISSUE TITLE
questions about num of test samples

### ISSUE THREAD

**Issue by Frank-Wang-wow** [SimingYan/HPNet#13]
Hi, Siming, thanks for the code and the dataset. I noticed that there are 4000 test samples in your test dataset, but I see that the test set written in your code is to take every 100th test sample as a test sample. I would like to ask whether the results in your paper are based on the full test set or the results of randomly selected partial samples for testing

**Comment by SimingYan** [comment]
Hi Frank,

Sorry for the late reply! I somehow miss the message. Taking every 100th test sample in the code is to speed up the testing phase because the full testset is too slow. But I report the number of full test set in the paper.

**Comment by Frank-Wang-wow** [comment]
Thank you very much for your reply, I also think that the full test once is too slow, hhh
