### ISSUE TITLE
CUDA out of memory

### ISSUE THREAD

**Issue by Tomoki-0526** [SimingYan/HPNet#15]
Thanks for your great work!

I'm running into a problem in the training part, it reports CUDA out of memory but there;s no any other program running on the gpu I select, and the memory is obviously sufficient.

Here are the error message and the infomation of my gpu. I wonder how to solve this and looking forward to your reply!

![屏幕截图 2022-12-12 153444](https://user-images.githubusercontent.com/73088234/206987752-a1cb5d97-605f-4f66-82eb-5be02b242121.png)
![屏幕截图 2022-12-12 153457](https://user-images.githubusercontent.com/73088234/206987760-a9bf8a14-ca44-4f23-aa60-d02bf253dd77.png)

**Comment by SimingYan** [comment]
I did not meet this problem before. And our model should be able to run with 24GB memory. Could you provide more details?
