### ISSUE TITLE
using cluster_pred to label input point cloud

### ISSUE THREAD

**Issue by Eusford** [SimingYan/HPNet#17]
As you mentioned in issue #4, the variable ```cluster_pred``` stores the color label of input point cloud, but I found the dimension 7000 not equal to the numbers of points. I think ```cluster_pred``` is a downsampling result via function ```torch.gather``` but how can I recover all input points?

**Comment by SimingYan** [comment]
Hi, I think maybe you can remove the subsample codes(comment the torch.gather lines)?

**Comment by Eusford** [comment]
But in the following code, the variables ```affinity_feat```, ```type_per_point```, ```param_per_point``` and ```sub_idx``` are already subsampled results through the model. Subject to your net structure, I may not be able to cancel the subsampling.

```
affinity_feat, type_per_point, param_per_point, sub_idx = self.model(inputs_xyz_th, inputs_n_th, postprocess=postprocess)
```

If I simply remove the ```torch.gather``` lines, there will be problems (dimensions not match) in the following postprocess part, as this part is based on the subsampled results.

**Comment by SimingYan** [comment]
I think that's because in the `model/dgcnn.py` file, we subsampled 7000 points: https://github.com/SimingYan/HPNet/blob/9be52adbd1e5d8a535492c21719b84bb5256beb7/models/dgcnn.py#L288. If you do not want to subsample, you should also take care of this line.

**Comment by Eusford** [comment]
Good, thanks for your help!
