### ISSUE TITLE
Get the parameters for a surface instance?

### ISSUE THREAD

**Issue by Eusford** [SimingYan/HPNet#18]
I found the output ```type_per_point``` and ```param_per_point``` for each point and I intended to assemble the parameters of all the points with same label in ```cluster_pred``` to calculate the parameters of a surface instance.

But it seemed that points with same label in ```cluster_pred``` didn't have same primitive type in ```type_per_point```, so I couldn't simply average these parameters. Can I get the parameters of surface instances from your code?

**Comment by SimingYan** [comment]
If I remember this correctly, our current codebase did not provide the primitive fitting code. I suggest you to move forward to [ParseNet](https://github.com/Hippogriff/parsenet-codebase) for the reference code.

**Comment by Eusford** [comment]
Ok, Thank you so much for your help!
