### ISSUE TITLE
Predicting segmentation without input normals

### ISSUE THREAD

**Issue by Vahe1994** [SimingYan/HPNet#19]
Hello! 
Thank you for your work. 
I have a small question about the pre-trained model. Is the provide pre-trained NN  only works for point cloud with normal's, or can I use it on point clouds without normal's? If it does not work, how can I predict segmentation for only PC inputs(maybe there is another pre-trained model for this)?

P.s. The question arose because in the code of models https://github.com/SimingYan/HPNet/blob/d63f52ce480cb2bbe791995d656f0a4a46db89c8/models/dgcnn.py#L362 it is hard coded to use normals . Also pre-trained model called abc_normals, which I assume judging by name required gt normal's as an input.

**Comment by SimingYan** [comment]
Hi,

Yes, the pre-trained model we provided only works with point clouds that have normals. However, our code is designed to support point clouds without normals as well. As you mentioned, you can switch the mode from 5 to 0 to use our code with point clouds lacking normals. Unfortunately, we don't have a pre-trained model for this case, but we encourage you to train one yourself. Good luck!

**Comment by Vahe1994** [comment]
Understood! Thank you very much for the quick reply:)
