### ISSUE TITLE
pretrained model broken

### ISSUE THREAD

**Issue by guohaoxiang** [SimingYan/HPNet#2]
The provided pretrained model (https://drive.google.com/file/d/1fj84kyD9CGT8j61IW-xSWZ5q4q5IpoYx/view?usp=sharing) seems to be broken, could you please upload a complete one?

**Comment by SimingYan** [comment]
Hi haoxiang,

I just rechecked this link and it works for me. Could you please share more details?

**Comment by guohaoxiang** [comment]
After downloading 'abc_normal.tar' and upzip it with 'tar -xvf abc_normal.tar', I got the following error:
![image](https://user-images.githubusercontent.com/29721619/128127383-04281cef-32d2-495e-9197-fd0f020729bb.png)

Could you please tell me the right way to unzip this file ?

**Comment by SimingYan** [comment]
You don't need to unzip this file. You can directly load it by `torch.load()`.

**Comment by guohaoxiang** [comment]
Thanks a lot for your help! My goal is to forward all test data.  I download the dataset 'ABC_final.zip' and unzip all files to './data/ABC' in the project folder. I also put 'abc_normal.tar' in the project folder. Then run 'python train.py --eval --checkpoint_path=abc_normal.tar--val_skip=100'  and get the following error:
![image](https://user-images.githubusercontent.com/29721619/128290590-acde55ad-6c93-46fc-a63b-79f0421f5228.png)

I check the 'inputs_xyz_th' and 'inputs_n_th' variables in Line 18-19 in 'train.py' and they are not empty, both with shape (1,10000, 3). Is there any clue to fix this bug?

**Comment by SimingYan** [comment]
I think it's because you are using 4 GPUs. The current code base only supports testing on 1 GPU.

**Comment by LuciusPennyworth** [comment]
During training, the current code will test one epoch every 10 epochs. If I use Multi-gpus in training, how can I use only one gpu for eval during training?

**Comment by SimingYan** [comment]
Thanks for the good question. I think the current codebase does not support multi-gpu testing. One simple suggestion is you can save the checkpoints and start another process for testing. But it's space-consuming.

 I tried to implement the multi-gpu support before, but I remember it would make the code very redundant. Sorry for any inconvenience.

**Comment by LuciusPennyworth** [comment]
OK, but do you have any clue to fix this problem? I check the code but didn't find anything suspicious.

**Comment by Kane-LAU** [comment]
> I think it's because you are using 4 GPUs. The current code base only supports testing on 1 GPU.

I use 4 GPU (Rtx4090) for training and it worked ，but occured issue when I switched to 1 GPU for testing 
```
### 1 GPU for  testing
export CUDA_VISIBLE_DEVICES=0


### test 
python train.py --eval --checkpoint_path="log/pretrained_models/checkpoint.tar" --data_path="../autodl-fs/ABC_final" --val_skip=100

```
here is bug track:
<img width="774" alt="image" src="https://github.com/SimingYan/HPNet/assets/42459125/6cb63b0b-f5df-4280-a75d-271f1edf1840">


how can i solve it ? Thank You so much!!!  😄
