### ISSUE TITLE
hi, about the mesh of the ABC Dataset for the computation of res error and P coverage.

### ISSUE THREAD

**Issue by hay-001** [SimingYan/HPNet#23]

**Comment by hay-001** [comment]
I noticed that you mentioned that your res error and Pverage metrics are implemented through Parsenet's code, but these two metrics require mesh data. The data provided by Parsenet does not seem to be directly consistent with the ABC Dataset of hpnet. I would like to ask if you have corresponding mesh data, or how you calculated these metrics in your experiments. Thanks！

**Comment by SimingYan** [comment]
Hi,

We apologize for any inconvenience. To compute the res error and P coverage, we transferred our model to the ParseNet codebase. So this component was not included in our original codebase :)
