### ISSUE TITLE
questions for the project

### ISSUE THREAD

**Issue by waldstein94** [SimingYan/HPNet#24]
Hello, Yan. I'm very thank you for sharing the codes! 
Project was very easy to set up. So again, thank you for saving my time! 

There's some questions for your projects. 
When I ran your code, I found number of primitive type used in project is set wtih 10. 
Then part of them are replaced with other index during evaluation. (I refered some functions in your project, "map_type_gt" and "compute_type_miou_abc".  Furthermore, the way of assignment is different in each function)
In the paper, the number of primitive type is set to 6 and I wonder the reason why you implement it in this way. 

Best.
Gahye

**Comment by SimingYan** [comment]
Hi Gahye,

Thanks for your interest! This is a good question. The reason we did this is because we follow the same way as ParseNet. They save the primitive type in 10 classes with only 6 unique classes. I think if you merge the 10 classes to 6, the result should be similar.

Best,
Siming
