### ISSUE TITLE
Can not unzip pre-trained models

### ISSUE THREAD

**Issue by MulinYu** [SimingYan/HPNet#3]
Hello,

Thanks for making your code available.

I downloaded your pre-trained model which is abc_normal.tar from your given link, but I can not unzip that file. Can you check if the file is broken?

best.
Mulin

**Comment by SimingYan** [comment]
Hi Mulin,

Thanks for your question!

I think you don't need to unzip this file. You can directly load it by` torch.load('abc_normal.tar')`.
