### ISSUE TITLE
Save output

### ISSUE THREAD

**Issue by MulinYu** [SimingYan/HPNet#4]
Hello Siming,

Can I save the output to a file such as '.h5' or '.ply' with your code?

Thanks in advance.
Best and have a nice day.

Mulin

**Comment by SimingYan** [comment]
Hi Mulin,

Of course. I think the easiest way is to use the prediction `cluster_pred` as the color label for the input point cloud. This variable is define here: https://github.com/SimingYan/HPNet/blob/8e374b646933e4e70705df0d62e3984e3ba6b961/train.py#L102.

**Comment by MulinYu** [comment]
> The current code base only provides the evaluation of segmentation IoU and type IoU. Please refer to [ParseNet](https://github.com/Hippogriff/parsenet-codebase) for the res-error and P-coverage evaluation.

Thanks for your reply, can I ask T_gt = '?' when a point belongs to a plane?

Best

**Comment by SimingYan** [comment]
I followed the setting from ParseNet. 
plane = 1; cone = 3; cylinder = 4; sphere = 5; open b-spline = 2, 8; close b-spline = 6, 7, 9.

**Comment by Eusford** [comment]
@SimingYan Hello, I found the variable ```cluster_pred``` always a tensor of size (1, 7000) for different input point clouds, not equals to the number of points. I wonder if it is right. If so, how to label input points, or else how to deal with it?

**Comment by Tomoki-0526** [comment]
It seems that the function ```torch.gather``` in ```train.py``` performs a downsampling, but it may be hard for me to restore the information of original points. Can you tell me how to visualize the results as shown in your paper?

**Comment by Eusford** [comment]
It seems that the function ```torch.gather``` in ```train.py``` performs a downsampling, but it may be hard for me to restore the information of original points. Can you tell me how to visualize the results as shown in your paper?
