### ISSUE TITLE
Meaning of "T_param" in the dataset

### ISSUE THREAD

**Issue by MulinYu** [SimingYan/HPNet#6]
Hello,

Can you explain a little bit what is the meaning of each dimension of "T_param"?

I know it's the parameters of plane, cone, sphere and cylinder. I think you follow the parameters defined in SPFN, can you describe it more precisely? For example, the first 3 dimensions is 'a' of a plane or the first dimension is 'd' of a plane?

Thanks in advance.

Best.
Mulin

**Comment by SimingYan** [comment]
Hi @MulinYu ,

Yeah, following the figure 3 in SPFN, I think T_param should be:
[sphere_c, sphere_r, plane_a, plane_d, cylinder_a, cylinder_c, cylinder_r, cone_a, cone_c, cone_theta].
