### ISSUE TITLE
ABC dataset id correspondence

### ISSUE THREAD

**Issue by guohaoxiang** [SimingYan/HPNet#7]
Hi, Siming. Thanks for providing the dataset, can you tell me where I can find the correpondence between your data id and the id of ABC dataset? That would be very helpful. Thanks.

**Comment by SimingYan** [comment]
Hi Haoxiang,

Thanks for your interest!

I apologize that I did not save the correspondence between my data and the origin ABC Dataset. But I evaluated ParseNet based on my database before and I could reproduce their result successfully. So if you want a direct comparison, I suggest you to implement our work on their codebase or  their work on my codebase(I'm sorry again if this would spend too much time...)
