### ISSUE TITLE
Questions about primitive parameter in dataset

### ISSUE THREAD

**Issue by LuciusPennyworth** [SimingYan/HPNet#9]
Hi Siming，
I wonder where is the primitive parameters information come in your dataset? I didn't find it in the origin ABC dataset, did you pre-process it from ABC dataset? And I also curious about the accuracy of directly predict primitive parameters from network, is it similar to the gt primitive parameters? 
Thanks in advance for your reply and wonderful code. It helps me a lot.~

**Comment by SimingYan** [comment]
Hi @LuciusPennyworth,

Thanks for your interest!
I upload our preprocessing scripts to the repo. Please check README.md for more details. The predicted primitive parameters are not very accurate but it still helps the segmentation task.

**Comment by LuciusPennyworth** [comment]
It's helpful! Thanks a lot!
